version: '3.9'
networks:
  traefik:
    external: true

services:
  error-pages:
    image: '${IMAGE_NAME}'
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-pages.entrypoints=websecure"
      - "traefik.http.routers.error-pages.priority=1" # This is important to make sure that others will be prioritized over this one
      - "traefik.http.routers.error-pages.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-pages.middlewares=error-pages-middleware"
      - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-pages-middleware.errors.service=error-pages-service"
      - "traefik.http.middlewares.error-pages-middleware.errors.query: /{status}.html"

      
      - "traefik.http.services.error-pages-service.loadbalancer.server.port=80"